#!/usr/bin/env python3
"""Generate a styled summaries HTML and release schedule from the `memories/` folders.

Usage:
  python generate_release_schedule.py

The script:
- Reads subfolders in `memories/` matching YYYY-MM-DD.
- Sorts them in reverse date order.
- Groups them into sets of 4 (for 22 releases if 88 folders exist).
- Assigns release dates starting today and every 4 days.
- Reads `summary.md` inside each folder if present and includes it in the HTML.
"""
import os
import re
import datetime
import math
from pathlib import Path


MEMORIES_DIR = Path('memories')
OUTPUT_FILE = Path('summaries.html')
GROUP_SIZE = 4


def is_iso_date(s):
    return re.match(r'^\d{4}-\d{2}-\d{2}$', s) is not None


def collect_folders():
    if not MEMORIES_DIR.exists():
        raise SystemExit(f"Directory not found: {MEMORIES_DIR}")
    folders = [p.name for p in MEMORIES_DIR.iterdir() if p.is_dir() and is_iso_date(p.name)]
    folders.sort(reverse=True)
    return folders


def read_summary(folder_name):
    p = MEMORIES_DIR / folder_name / 'summary.md'
    if p.exists():
        return p.read_text(encoding='utf-8')
    return None


def list_files(folder_name):
    p = MEMORIES_DIR / folder_name
    items = []
    for child in sorted(p.iterdir()):
        if child.is_file():
            items.append(child.name)
    return items


def generate_html(groups, start_date):
    html_parts = []
    html_parts.append('<!doctype html>')
    html_parts.append('<html lang="en">')
    html_parts.append('<head>')
    html_parts.append('<meta charset="utf-8">')
    html_parts.append('<meta name="viewport" content="width=device-width,initial-scale=1">')
    html_parts.append('<title>Memories Release Schedule</title>')
    html_parts.append('<style>')
    html_parts.append('body{font-family: system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:980px;margin:24px auto;padding:0 16px;color:#111}')
    html_parts.append('.group{border:1px solid #e6e6e6;padding:12px;margin:12px 0;border-radius:8px;background:#fff}')
    html_parts.append('.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}')
    html_parts.append('.date{font-weight:600;color:#0b66ff}')
    html_parts.append('.folder{margin:6px 0;padding:8px;border-radius:6px;background:#fbfbfd;border:1px solid #f0f0f3}')
    html_parts.append('.summary{white-space:pre-wrap;margin-top:8px;color:#333}')
    html_parts.append('</style>')
    html_parts.append('</head>')
    html_parts.append('<body>')
    html_parts.append('<h1>Memories Release Schedule</h1>')
    html_parts.append('<p>Generated on: ' + start_date.isoformat() + '</p>')

    for i, group in enumerate(groups):
        rel_date = start_date + datetime.timedelta(days=4 * i)
        html_parts.append(f'<div class="group">')
        html_parts.append(f'<div class="header"><div><strong>Release #{i+1}</strong></div><div class="date">{rel_date.isoformat()}</div></div>')
        for folder in group:
            files = list_files(folder)
            summary = read_summary(folder)
            html_parts.append(f'<div class="folder"><div><strong>{folder}</strong> &nbsp;(<a href="{MEMORIES_DIR}/{folder}/">open folder</a>)</div>')
            if files:
                html_parts.append('<div class="files"><em>Files:</em> ' + ', '.join(files) + '</div>')
            if summary:
                safe = summary.replace('<','&lt;').replace('>','&gt;')
                html_parts.append('<div class="summary">' + safe + '</div>')
            else:
                html_parts.append('<div class="summary"><em>No summary.md found — add one in the folder to display styled content here.</em></div>')
            html_parts.append('</div>')
        html_parts.append('</div>')

    html_parts.append('<footer><p style="color:#666;font-size:0.9rem">This file was generated by generate_release_schedule.py.</p></footer>')
    html_parts.append('</body></html>')
    return '\n'.join(html_parts)


def main():
    folders = collect_folders()
    total = len(folders)
    print(f"Found {total} memory folders in {MEMORIES_DIR}/")
    if total == 0:
        raise SystemExit('No memory folders found.')

    groups = [folders[i:i+GROUP_SIZE] for i in range(0, total, GROUP_SIZE)]
    print(f"Grouped into {len(groups)} groups of up to {GROUP_SIZE} (expected 22 if 88 folders).")

    start_date = datetime.date.today()
    html = generate_html(groups, start_date)
    OUTPUT_FILE.write_text(html, encoding='utf-8')
    print(f"Wrote {OUTPUT_FILE} — open it in a browser to view the styled summaries.")


if __name__ == '__main__':
    main()
